# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addvm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addVM(object):
    def setupUi(self, addVM, datadict):
        addVM.setObjectName("addVM")
        addVM.setWindowModality(QtCore.Qt.ApplicationModal)
        addVM.resize(580, 250)
        self.datadict = datadict
        self.importCheckbox = QtWidgets.QCheckBox(addVM)
        self.importCheckbox.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.importCheckbox.setObjectName("importCheckbox")
        self.lineEdit = QtWidgets.QLineEdit(addVM)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 481, 29))
        self.lineEdit.setObjectName("lineEdit")
        self.browseImport = QtWidgets.QPushButton(addVM)
        self.browseImport.setGeometry(QtCore.QRect(490, 30, 86, 31))
        self.browseImport.setObjectName("browseImport")
        self.lineEdit_2 = QtWidgets.QLineEdit(addVM)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 80, 471, 29))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(addVM)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 110, 471, 29))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.nameLabel = QtWidgets.QLabel(addVM)
        self.nameLabel.setGeometry(QtCore.QRect(10, 80, 71, 31))
        self.nameLabel.setObjectName("nameLabel")
        self.descriptionLabel = QtWidgets.QLabel(addVM)
        self.descriptionLabel.setGeometry(QtCore.QRect(10, 114, 91, 21))
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.label_3 = QtWidgets.QLabel(addVM)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 63, 21))
        self.label_3.setObjectName("label_3")
        self.vmPathLabel = QtWidgets.QLabel(addVM)
        self.vmPathLabel.setGeometry(QtCore.QRect(60, 150, 511, 21))
        self.vmPathLabel.setObjectName("vmPathLabel")
        self.startVMcheck = QtWidgets.QCheckBox(addVM)
        self.startVMcheck.setGeometry(QtCore.QRect(10, 180, 151, 20))
        self.startVMcheck.setObjectName("startVMcheck")
        self.configureCheck = QtWidgets.QCheckBox(addVM)
        self.configureCheck.setGeometry(QtCore.QRect(170, 180, 181, 20))
        self.configureCheck.setObjectName("configureCheck")
        self.addButton = QtWidgets.QPushButton(addVM)
        self.addButton.setGeometry(QtCore.QRect(400, 210, 86, 31))
        self.addButton.setDefault(True)
        self.addButton.setObjectName("addButton")
        self.cancelButton = QtWidgets.QPushButton(addVM)
        self.cancelButton.setGeometry(QtCore.QRect(490, 210, 86, 31))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(addVM)
        QtCore.QMetaObject.connectSlotsByName(addVM)

        self.addButton.clicked.connect(self.addButtonClicked)
        self.cancelButton.clicked.connect(self.cancelButtonClicked)

    def retranslateUi(self, addVM):
        _translate = QtCore.QCoreApplication.translate
        addVM.setWindowTitle(_translate("addVM", "Add VM"))
        self.importCheckbox.setText(_translate("addVM", "Import VM"))
        self.browseImport.setText(_translate("addVM", "Browse"))
        self.nameLabel.setText(_translate("addVM", "Name:"))
        self.descriptionLabel.setText(_translate("addVM", "Description:"))
        self.label_3.setText(_translate("addVM", "Path:"))
        self.vmPathLabel.setText(_translate("addVM", "C:\\I like VMs\\And Potatoes\\"))
        self.startVMcheck.setText(_translate("addVM", "Start this VM now"))
        self.configureCheck.setText(_translate("addVM", "Configure this VM now"))
        self.addButton.setText(_translate("addVM", "Add"))
        self.cancelButton.setText(_translate("addVM", "Cancel"))

    def addButtonClicked(self):
        self.lineEdit.setText(self.datadict["testing"])

    def cancelButtonClicked(self):
        self.datadict[self.lineEdit_2.text()] = "it worked"
