# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/addvm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addVM(object):
    def setupUi(self, addVM):
        addVM.setObjectName("addVM")
        addVM.setWindowModality(QtCore.Qt.ApplicationModal)
        addVM.resize(580, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(addVM)
        self.verticalLayout.setObjectName("verticalLayout")
        self.importCheckbox = QtWidgets.QCheckBox(addVM)
        self.importCheckbox.setObjectName("importCheckbox")
        self.verticalLayout.addWidget(self.importCheckbox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(addVM)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.browseImport = QtWidgets.QPushButton(addVM)
        self.browseImport.setEnabled(False)
        self.browseImport.setObjectName("browseImport")
        self.horizontalLayout.addWidget(self.browseImport)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(addVM)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.lineEdit_2 = QtWidgets.QLineEdit(addVM)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.descriptionLabel = QtWidgets.QLabel(addVM)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.descriptionLabel)
        self.lineEdit_3 = QtWidgets.QLineEdit(addVM)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_3 = QtWidgets.QLabel(addVM)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.vmPathLabel = QtWidgets.QLabel(addVM)
        self.vmPathLabel.setObjectName("vmPathLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vmPathLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startVMcheck = QtWidgets.QCheckBox(addVM)
        self.startVMcheck.setObjectName("startVMcheck")
        self.horizontalLayout_2.addWidget(self.startVMcheck)
        self.configureCheck = QtWidgets.QCheckBox(addVM)
        self.configureCheck.setObjectName("configureCheck")
        self.horizontalLayout_2.addWidget(self.configureCheck)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.addButton = QtWidgets.QPushButton(addVM)
        self.addButton.setDefault(True)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        self.cancelButton = QtWidgets.QPushButton(addVM)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(addVM)
        QtCore.QMetaObject.connectSlotsByName(addVM)

    def retranslateUi(self, addVM):
        _translate = QtCore.QCoreApplication.translate
        addVM.setWindowTitle(_translate("addVM", "Add VM"))
        self.importCheckbox.setText(_translate("addVM", "Import VM"))
        self.browseImport.setText(_translate("addVM", "Browse"))
        self.nameLabel.setText(_translate("addVM", "Name:"))
        self.descriptionLabel.setText(_translate("addVM", "Description:"))
        self.label_3.setText(_translate("addVM", "Path:"))
        self.vmPathLabel.setText(_translate("addVM", "C:\\I like VMs\\And Potatoes\\"))
        self.startVMcheck.setText(_translate("addVM", "Start this VM now"))
        self.configureCheck.setText(_translate("addVM", "Configure this VM now"))
        self.addButton.setText(_translate("addVM", "Add"))
        self.cancelButton.setText(_translate("addVM", "Cancel"))
