# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editVM(object):
    def setupUi(self, editVM):
        editVM.setObjectName("editVM")
        editVM.setWindowModality(QtCore.Qt.ApplicationModal)
        editVM.resize(580, 180)
        self.verticalLayout = QtWidgets.QVBoxLayout(editVM)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(editVM)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.vmName = QtWidgets.QLineEdit(editVM)
        self.vmName.setObjectName("vmName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vmName)
        self.descriptionLabel = QtWidgets.QLabel(editVM)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.descriptionLabel)
        self.vmDescription = QtWidgets.QLineEdit(editVM)
        self.vmDescription.setObjectName("vmDescription")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vmDescription)
        self.label_3 = QtWidgets.QLabel(editVM)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vmPath = QtWidgets.QLineEdit(editVM)
        self.vmPath.setObjectName("vmPath")
        self.horizontalLayout_3.addWidget(self.vmPath)
        self.pathBrowse = QtWidgets.QPushButton(editVM)
        self.pathBrowse.setObjectName("pathBrowse")
        self.horizontalLayout_3.addWidget(self.pathBrowse)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startVMcheck = QtWidgets.QCheckBox(editVM)
        self.startVMcheck.setObjectName("startVMcheck")
        self.horizontalLayout_2.addWidget(self.startVMcheck)
        self.configureCheck = QtWidgets.QCheckBox(editVM)
        self.configureCheck.setObjectName("configureCheck")
        self.horizontalLayout_2.addWidget(self.configureCheck)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.editButton = QtWidgets.QPushButton(editVM)
        self.editButton.setDefault(True)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.cancelButton = QtWidgets.QPushButton(editVM)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(editVM)
        QtCore.QMetaObject.connectSlotsByName(editVM)

    def retranslateUi(self, editVM):
        _translate = QtCore.QCoreApplication.translate
        editVM.setWindowTitle(_translate("editVM", "Edit VM"))
        self.nameLabel.setText(_translate("editVM", "Name:"))
        self.descriptionLabel.setText(_translate("editVM", "Description:"))
        self.label_3.setText(_translate("editVM", "Path:"))
        self.pathBrowse.setText(_translate("editVM", "Browse"))
        self.startVMcheck.setText(_translate("editVM", "Start this VM now"))
        self.configureCheck.setText(_translate("editVM", "Configure this VM now"))
        self.editButton.setText(_translate("editVM", "Edit"))
        self.cancelButton.setText(_translate("editVM", "Cancel"))
