# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/Edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editVM(object):
    def setupUi(self, editVM):
        editVM.setObjectName("editVM")
        editVM.setWindowModality(QtCore.Qt.ApplicationModal)
        editVM.resize(580, 180)
        self.vmName = QtWidgets.QLineEdit(editVM)
        self.vmName.setGeometry(QtCore.QRect(100, 10, 471, 29))
        self.vmName.setObjectName("vmName")
        self.vmDescription = QtWidgets.QLineEdit(editVM)
        self.vmDescription.setGeometry(QtCore.QRect(100, 40, 471, 29))
        self.vmDescription.setObjectName("vmDescription")
        self.nameLabel = QtWidgets.QLabel(editVM)
        self.nameLabel.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.nameLabel.setObjectName("nameLabel")
        self.descriptionLabel = QtWidgets.QLabel(editVM)
        self.descriptionLabel.setGeometry(QtCore.QRect(10, 44, 91, 21))
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.label_3 = QtWidgets.QLabel(editVM)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.label_3.setObjectName("label_3")
        self.startVMcheck = QtWidgets.QCheckBox(editVM)
        self.startVMcheck.setGeometry(QtCore.QRect(10, 110, 151, 20))
        self.startVMcheck.setObjectName("startVMcheck")
        self.configureCheck = QtWidgets.QCheckBox(editVM)
        self.configureCheck.setGeometry(QtCore.QRect(170, 110, 181, 20))
        self.configureCheck.setObjectName("configureCheck")
        self.editButton = QtWidgets.QPushButton(editVM)
        self.editButton.setGeometry(QtCore.QRect(400, 140, 86, 31))
        self.editButton.setDefault(True)
        self.editButton.setObjectName("editButton")
        self.cancelButton = QtWidgets.QPushButton(editVM)
        self.cancelButton.setGeometry(QtCore.QRect(490, 140, 86, 31))
        self.cancelButton.setObjectName("cancelButton")
        self.vmPath = QtWidgets.QLineEdit(editVM)
        self.vmPath.setGeometry(QtCore.QRect(100, 70, 381, 29))
        self.vmPath.setObjectName("vmPath")
        self.pathBrowse = QtWidgets.QPushButton(editVM)
        self.pathBrowse.setGeometry(QtCore.QRect(480, 70, 91, 31))
        self.pathBrowse.setObjectName("pathBrowse")

        self.retranslateUi(editVM)
        QtCore.QMetaObject.connectSlotsByName(editVM)

    def retranslateUi(self, editVM):
        _translate = QtCore.QCoreApplication.translate
        editVM.setWindowTitle(_translate("editVM", "Edit VM"))
        self.nameLabel.setText(_translate("editVM", "Name:"))
        self.descriptionLabel.setText(_translate("editVM", "Description:"))
        self.label_3.setText(_translate("editVM", "Path:"))
        self.startVMcheck.setText(_translate("editVM", "Start this VM now"))
        self.configureCheck.setText(_translate("editVM", "Configure this VM now"))
        self.editButton.setText(_translate("editVM", "Edit"))
        self.cancelButton.setText(_translate("editVM", "Cancel"))
        self.pathBrowse.setText(_translate("editVM", "Browse"))
