# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.addButton.setObjectName("addButton")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(50, 10, 41, 31))
        self.editButton.setObjectName("editButton")
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(90, 10, 61, 31))
        self.removeButton.setObjectName("removeButton")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(170, 10, 86, 31))
        self.startButton.setObjectName("startButton")
        self.configButton = QtWidgets.QPushButton(self.centralwidget)
        self.configButton.setGeometry(QtCore.QRect(260, 10, 86, 31))
        self.configButton.setObjectName("configButton")
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(580, 10, 86, 31))
        self.settingsButton.setObjectName("settingsButton")
        self.vmTable = QtWidgets.QTableWidget(self.centralwidget)
        self.vmTable.setGeometry(QtCore.QRect(10, 50, 661, 441))
        self.vmTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.vmTable.setRowCount(0)
        self.vmTable.setColumnCount(4)
        self.vmTable.setObjectName("vmTable")
        item = QtWidgets.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.vmTable.setHorizontalHeaderItem(3, item)
        self.vmTable.horizontalHeader().setCascadingSectionResizes(False)
        self.vmTable.horizontalHeader().setStretchLastSection(True)
        self.vmTable.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "86Box Manager Lite"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.configButton.setText(_translate("MainWindow", "Configure"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        item = self.vmTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.vmTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.vmTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.vmTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Path"))
